version: '3'

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
          - "5000:5000"
    volumes:
          - data:/opt/dogfound/data
  neural_network:
    build:
      context: ./neural_network
      dockerfile: Dockerfile
    ports:
          - "6002:80"
    volumes:
          - data:/opt/dogfound/data
volumes:
  data: